In [1]:
import os
os.getcwd()

'C:\\Users\\ASHA\\Desktop\\intern\\dataset'

# importing the health monitoring dataset and required libraries and performing some basic operations on the dataset

In [2]:
import numpy as np
import pandas as pd
data1=pd.read_csv("Health monitoring.csv")
data1

SBP  DBP  Pulse  Temperature  Level
0    120   80     80           98      0
1    140   83     75          100      1
2    155  100     92          104      2
3    115   82     79           97      0
4    119   79     85          102      1
..   ...  ...    ...          ...    ...
144  154   99     83          103      2
145  118   77     73           98      0
146  125   87     79          102      1
147  132   88     78          101      1
148  118   82     74           98      0

[149 rows x 5 columns]

In [3]:
data1=pd.read_csv("Health monitoring.csv",nrows=3)

In [4]:
data1

SBP  DBP  Pulse  Temperature  Level
0  120   80     80           98      0
1  140   83     75          100      1
2  155  100     92          104      2

In [5]:
data1.describe()

SBP         DBP      Pulse  Temperature  Level
count    3.000000    3.000000   3.000000     3.000000    3.0
mean   138.333333   87.666667  82.333333   100.666667    1.0
std     17.559423   10.785793   8.736895     3.055050    1.0
min    120.000000   80.000000  75.000000    98.000000    0.0
25%    130.000000   81.500000  77.500000    99.000000    0.5
50%    140.000000   83.000000  80.000000   100.000000    1.0
75%    147.500000   91.500000  86.000000   102.000000    1.5
max    155.000000  100.000000  92.000000   104.000000    2.0

In [6]:
data1.cov()

SBP         DBP      Pulse  Temperature  Level
SBP          308.333333  169.166667  95.833333    51.666667   17.5
DBP          169.166667  116.333333  85.666667    32.333333   10.0
Pulse         95.833333   85.666667  76.333333    21.666667    6.0
Temperature   51.666667   32.333333  21.666667     9.333333    3.0
Level         17.500000   10.000000   6.000000     3.000000    1.0

from the above observation we can see the  high positive variance between the SBP and DBP

In [7]:
data1.corr()

SBP       DBP     Pulse  Temperature     Level
SBP          1.000000  0.893208  0.624668     0.963123  0.996616
DBP          0.893208  1.000000  0.909081     0.981251  0.927146
Pulse        0.624668  0.909081  1.000000     0.811739  0.686743
Temperature  0.963123  0.981251  0.811739     1.000000  0.981981
Level        0.996616  0.927146  0.686743     0.981981  1.000000

From the above observation we can see that all the paramyters have positive correlation between each other so there will be a relation between them

In [8]:
data1.head()

SBP  DBP  Pulse  Temperature  Level
0  120   80     80           98      0
1  140   83     75          100      1
2  155  100     92          104      2

In [9]:
data1.head(n=2)

SBP  DBP  Pulse  Temperature  Level
0  120   80     80           98      0
1  140   83     75          100      1

In [10]:
data1.tail()

SBP  DBP  Pulse  Temperature  Level
0  120   80     80           98      0
1  140   83     75          100      1
2  155  100     92          104      2

In [11]:
data1.columns

Index(['SBP', 'DBP', 'Pulse', 'Temperature', 'Level'], dtype='object')

In [12]:
data1.dtypes

SBP            int64
DBP            int64
Pulse          int64
Temperature    int64
Level          int64
dtype: object

In [13]:
data1['Temperature'].unique()#returns unique values of temperature

array([ 98, 100, 104], dtype=int64)

In [14]:
data1['SBP'].unique()#returns unique values of SBP(Spontaneous bacterial peritonitis)

array([120, 140, 155], dtype=int64)

In [15]:
data1['DBP'].unique()#returns unique values of DBP(Diastolic blood pressure)

array([ 80,  83, 100], dtype=int64)

In [23]:
data1['Pulse'].unique()#returns unique values of Pulse

array([80, 75, 92], dtype=int64)

In [24]:
data1[0:3]

SBP  DBP  Pulse  Temperature  Level
0  120   80     80           98      0
1  140   83     75          100      1
2  155  100     92          104      2

In [25]:
mean_Temperature=data1['Temperature'].mean()#returns mean of temperature values

In [18]:
mean_Temperature

100.66666666666667

In [26]:
mean_SBP=data1['SBP'].mean()#returns mean of SBP values

In [27]:
mean_SBP

138.33333333333334

In [28]:
mean_DBP=data1['DBP'].mean()#returns mean of DBP values

In [29]:
mean_DBP

87.66666666666667

In [30]:
mean_Pulse=data1['Pulse'].mean()#returns mean of pulse values

In [31]:
mean_Pulse

82.33333333333333

In [33]:
data1.shape

(3, 5)

In [34]:
data1.pivot_table(data1,index=['SBP'])

DBP  Level  Pulse  Temperature
SBP                                
120   80      0     80           98
140   83      1     75          100
155  100      2     92          104

In [35]:
data1.pivot_table(data1,index=['DBP'])

Level  Pulse  SBP  Temperature
DBP                                
80       0     80  120           98
83       1     75  140          100
100      2     92  155          104

In [36]:
data1.pivot_table(data1,index=['Temperature'])

DBP  Level  Pulse  SBP
Temperature                        
98            80      0     80  120
100           83      1     75  140
104          100      2     92  155

In [37]:
data1.pivot_table(data1,index=['Pulse'])

DBP  Level  SBP  Temperature
Pulse                              
75      83      1  140          100
80      80      0  120           98
92     100      2  155          104

In [38]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   SBP          3 non-null      int64
 1   DBP          3 non-null      int64
 2   Pulse        3 non-null      int64
 3   Temperature  3 non-null      int64
 4   Level        3 non-null      int64
dtypes: int64(5)
memory usage: 248.0 bytes


In [39]:
data1['Temperature'].value_counts()

98     1
104    1
100    1
Name: Temperature, dtype: int64

In [40]:
data1['Level'].value_counts()

2    1
1    1
0    1
Name: Level, dtype: int64

In [41]:
data1['SBP'].value_counts()

155    1
140    1
120    1
Name: SBP, dtype: int64

In [42]:
data1['DBP'].value_counts()

83     1
100    1
80     1
Name: DBP, dtype: int64

In [46]:
import matplotlib.pyplot as plt
%matplotlib inline
#librarie used for visualization